baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Planning with Data"
theme = "hyde"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/post/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight=-1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    

[[menu.contact]]
    name = "GitHub"
    url = "https://github.com/frankmuraca"
[[menu.contact]]
    name = "Twitter"
    url = "https://twitter.com/frankmuraca"


[params]
    description = "Helping planners understand their communities with data & analytics"
    show_post_front = true
    n_post_front = 5
    show_projects_front = true
    # Change contactHeader text
    # Or comment out to use <hr> instead
    contactHeader = "Contact Me"

    # Change Hyde theme
    themeColor = "theme-base-0d"
    # Overide or add custom CSS styles
    #customCSS = "/css/custom.css"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
